name=input("what is your name?")
quest=input("what is our quest?")
color=input("what is your fav color?")
print("your name is " +   name + '.')
print("our quest is "  +  quest + ".")
print("my fav color is " +  color + ".")
print(type(name))